# Generated by Django 4.2.10 on 2024-03-09 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='place')),
                ('time', models.TimeField(verbose_name='time')),
                ('action', models.CharField(max_length=200, verbose_name='action')),
                ('is_nice_habit', models.BooleanField(blank=True, null=True, verbose_name='is_nice_habit')),
                ('period', models.CharField(choices=[('HOUR', 'one time in hour'), ('DAY', 'one time in day'), ('WEEK', 'one time in week')], default='DAY', max_length=20, verbose_name='period')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='reward')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='duration')),
                ('is_public', models.BooleanField(default=False, verbose_name='is_public')),
                ('nice_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='nice_habit')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
            },
        ),
    ]
